// Copyright (c) 2004-2020 Microchip Technology Inc. and its subsidiaries.
// SPDX-License-Identifier: MIT

:sectnumlevels: 5
:toclevels: 5

= MERA General

== Instance Creation
Initialization starts by creating a MERA instance using `mera_create()`:

* Callback functions to read/write RTE registers must be provided.
* Callback functions to lock/unlock MERA may be provided for thread protection.
* Callback functions to trace MERA function calls may be provided.

== Polling
Polling of counters should be done at least once per second by calling `mera_poll()`.

== Timers
Timers are controlled based on a Super Cycle of one second as shown below.
Each timer (`mera_time_t`) has two fields:

* Offset: Determines the first timeout in a Super Cycle, may be set to
`MERA_TIME_OFFSET_NONE` to disable the offset.
* Interval: Determines the next timeouts in a Super Cycle. 

image::./timer.svg[align=center]

== Input/Output Addresses
The `mera_addr_t` type is used to setup input/output addresses for read/write operations.
This type includes the interface type (e.g. SRAM) and address value.

== Debug Trace
The MERA code uses trace macros, which can be used for debug purposes.
Debug levels can be controlled per group using `mera_trace_conf_set()`.

== Debug Print
Debugging can also be done using `mera_debug_info_print()`.
MERA state and RTE registers are printed using the provided print callback function.

== API Function List
`mera_create()` +
`mera_destroy()` +
`mera_poll()` +
`mera_trace_conf_get()` +
`mera_trace_conf_set()` +
`mera_debug_info_get()` +
`mera_debug_info_print()`


