// Copyright (c) 2004-2020 Microchip Technology Inc. and its subsidiaries.
// SPDX-License-Identifier: MIT

:sectnumlevels: 5
:toclevels: 5

= Switch Core

== MESA
If MESA is used to control the Switch Core, the RTE port and Real Time Classification
must be done as described in the following sections.

=== RTE Port
The RTE is associated with port 4 of the switch. It is recommended that this 
port is placed as the last port in the port map and setup with interface type
MESA_PORT_INTERFACE_NO_CONNECTION. This is done to ensure that frames classified
as RTP frames can be forwarded to the RTE.

=== Real Time Classification
Classification to an RTP ID requires the following:

* The (VID, PCP) is enabled for Real Time classification (VID zero means untagged frames).
* The frame is matched by an RCL rule mapping to an RTP ID and forwarding to the RTE port.

See the MESA documentation for more details on RCL classification.

== SwitchDev
If the Linux SwitchDev driver is used to control the Switch Core, the RTE port and
Real Time Classification must be done as described in the following sections.

=== RTE Port
Forwarding to the RTE port must be enabled using a register write operation:

[source,shell]
----
symreg qsys_sw_port_mode[4] 0x45000
----

=== Real Time Classification
The (VID, PCP) values must be enabled for Real Time classification using register write operations.
Up to 8 VLANs can be enabled. The example below enables untagged classification for all PCPs:

[source,shell]
----
symreg ana_rt_vlan_pcp[0].pcp_mask 0xff
symreg ana_rt_vlan_pcp[0].vlan_id 0
symreg ana_rt_vlan_pcp[0].vlan_pcp_ena 1
----

Frames must then be classified to an RTP ID using a VCAP rule. The following example matches this:

* VLAN index (rt_vlan_idx 0) setup above.
* Profinet frames (rt_type 1)
* FrameID (rt_frmid 0x8765)

Matching frames are mapped to an RTP ID (rtp_id 3) and forwarded to port 4 (fwd_mask 0x10).

[source,shell]
----
vcap add is1 1 1 s1_rt first 0 rt_vlan_idx 0 0x7 rt_type 1 0x3 rt_frmid 0x8765 0xffff s1_rt rtp_id 3 fwd_ena 1 fwd_mask 0x10
----

== Common

=== QSPI

If QSPI is used for data transfers, this must also be setup.
The following commands are used to setup QSPI under Linux on the MCHP reference board.

[source,shell]
----
mount -t configfs none /sys/kernel/config
mkdir -p /sys/kernel/config/device-tree/overlays/tsys01
cat /overlays/qspi_overlay.dtbo > /sys/kernel/config/device-tree/overlays/tsys01/dtbo
----
